# Generated by Django 5.0.6 on 2024-06-26 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_id', models.CharField(max_length=255)),
                ('certificate', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'CERTIFICATE',
                'managed': False,
            },
        ),
    ]
