# Generated by Django 5.0.6 on 2024-06-28 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_certificate'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewMarks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criteria', models.CharField(blank=True, db_column='criteria', max_length=500, null=True)),
                ('rating', models.IntegerField(blank=True, null=True)),
                ('feedback', models.CharField(max_length=500)),
                ('total_marks', models.IntegerField()),
            ],
            options={
                'db_table': 'SUBMISSION_REVIEW',
                'managed': False,
            },
        ),
    ]
