# Generated by Django 5.0.6 on 2024-07-04 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_reviewmarks'),
    ]

    operations = [
        migrations.CreateModel(
            name='Abstract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abstract', models.CharField(max_length=255)),
                ('created_on', models.DateTimeField()),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(max_length=100)),
                ('remarks', models.CharField(max_length=500)),
            ],
            options={
                'db_table': 'ABSTRACT',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ReviewSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criteria', models.CharField(blank=True, db_column='criteria', max_length=500, null=True)),
                ('rating', models.IntegerField(blank=True, null=True)),
                ('feedback', models.CharField(max_length=500)),
                ('total_marks', models.IntegerField()),
            ],
            options={
                'db_table': 'SUBMISSION_REVIEW',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('mode', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'TIMESLOTS',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='ReviewMarks',
        ),
    ]
